apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: web
  labels:
    env: test
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: dordidora/web:1.0.0
          ports:
            - containerPort: 8000
